//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emedchina.TradeAssistant.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=testcen;Persist Security Info=True;User ID=zh_ndmain_dev;Password=zh_" +
            "ndmain_dev;Unicode=True")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Help.chm")]
        public string HelpUrl {
            get {
                return ((string)(this["HelpUrl"]));
            }
            set {
                this["HelpUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string userInfoEdit {
            get {
                return ((string)(this["userInfoEdit"]));
            }
            set {
                this["userInfoEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyncLimit {
            get {
                return ((bool)(this["SyncLimit"]));
            }
            set {
                this["SyncLimit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\DB\\TradeAssistantSal" +
            "er.mdb;Persist Security Info=True")]
        public string TradeAssistantSalerConnectionString {
            get {
                return ((string)(this["TradeAssistantSalerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=testcen;Persist Security Info=True;User ID=zh_ndmain_dev;Password=zh_" +
            "ndmain_dev;Unicode=True")]
        public string ConnectionString1 {
            get {
                return ((string)(this["ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal?isMenuFlag=1&handlerId=contract.conmerchandisedir&operate=List&orgTypeFlag" +
            "=2&currModuleID=USER00000000000000580669")]
        public string DirSearch {
            get {
                return ((string)(this["DirSearch"]));
            }
            set {
                this["DirSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal?isMenuFlag=1&handlerId=trade.orderquery&operate=OrderItemList&currModuleID" +
            "=USER00000000000000660664")]
        public string OrderList {
            get {
                return ((string)(this["OrderList"]));
            }
            set {
                this["OrderList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal?isMenuFlag=1&handlerId=contract.contractquery&operate=ConList&currModuleID" +
            "=USER00000000000000580671")]
        public string ContractList {
            get {
                return ((string)(this["ContractList"]));
            }
            set {
                this["ContractList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal?isMenuFlag=1&handlerId=user.user&operate=UpdateUserInfo&updatePassOnly=tru" +
            "e&currModuleID=USER00000000000000581649")]
        public string UserPassWord {
            get {
                return ((string)(this["UserPassWord"]));
            }
            set {
                this["UserPassWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal?isMenuFlag=1&handlerId=contract.contractsign&operate=ConList&currModuleID=" +
            "USER00000000000000580670")]
        public string ContractSign {
            get {
                return ((string)(this["ContractSign"]));
            }
            set {
                this["ContractSign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal?isMenuFlag=1&handlerId=contract.contractchange&operate=ConChgList&currModu" +
            "leID=INIT10000000000000000028")]
        public string ContractUpdate {
            get {
                return ((string)(this["ContractUpdate"]));
            }
            set {
                this["ContractUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal?isMenuFlag=1&handlerId=trade.sellerreturn&operate=ListConfirm&currModuleID" +
            "=USER00000000000000580674")]
        public string ReturnList {
            get {
                return ((string)(this["ReturnList"]));
            }
            set {
                this["ReturnList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal?isMenuFlag=1&handlerId=gpo.member.notice&operate=List&currModuleID=USER000" +
            "00000000000619845")]
        public string NoticeList {
            get {
                return ((string)(this["NoticeList"]));
            }
            set {
                this["NoticeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal?isMenuFlag=1&handlerId=trade.saler.sms&operate=SmsUserList&currModuleID=US" +
            "ER00000000000000241086")]
        public string SmsNo {
            get {
                return ((string)(this["SmsNo"]));
            }
            set {
                this["SmsNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://210.51.183.138/yunnan/")]
        public string WebSite {
            get {
                return ((string)(this["WebSite"]));
            }
            set {
                this["WebSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://202.96.54.112:8867/")]
        public string UpdateUrl {
            get {
                return ((string)(this["UpdateUrl"]));
            }
            set {
                this["UpdateUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portal?isMenuFlag=1&handlerId=user.user&operate=UpdateUserInfo&currModuleID=USER0" +
            "0000000000000581659")]
        public string userInfo {
            get {
                return ((string)(this["userInfo"]));
            }
            set {
                this["userInfo"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\DB\\TradeAssistant.mdf;I" +
            "ntegrated Security=True;Connect Timeout=30;Pooling=false;User Instance=True")]
        public string TempTradeConnectionString {
            get {
                return ((string)(this["TempTradeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\bin\\Debug\\DB\\TradeAssis" +
            "tant.mdf;Integrated Security=True;User Instance=True")]
        public string TradeAssistantConnectionString {
            get {
                return ((string)(this["TradeAssistantConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\DB\\TempTrade.mdf;Integr" +
            "ated Security=True;User Instance=True")]
        public string TempTradeConnectionString1 {
            get {
                return ((string)(this["TempTradeConnectionString1"]));
            }
        }
    }
}
