//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Emedchina.TradeAssistant.Client.UI.Report.ReportData {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("InvoiceDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class InvoiceDataSet : global::System.Data.DataSet {
        
        private HC_ORD_INVOICE_FROMDataTable tableHC_ORD_INVOICE_FROM;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public InvoiceDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected InvoiceDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["HC_ORD_INVOICE_FROM"] != null)) {
                    base.Tables.Add(new HC_ORD_INVOICE_FROMDataTable(ds.Tables["HC_ORD_INVOICE_FROM"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public HC_ORD_INVOICE_FROMDataTable HC_ORD_INVOICE_FROM {
            get {
                return this.tableHC_ORD_INVOICE_FROM;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            InvoiceDataSet cln = ((InvoiceDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["HC_ORD_INVOICE_FROM"] != null)) {
                    base.Tables.Add(new HC_ORD_INVOICE_FROMDataTable(ds.Tables["HC_ORD_INVOICE_FROM"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableHC_ORD_INVOICE_FROM = ((HC_ORD_INVOICE_FROMDataTable)(base.Tables["HC_ORD_INVOICE_FROM"]));
            if ((initTable == true)) {
                if ((this.tableHC_ORD_INVOICE_FROM != null)) {
                    this.tableHC_ORD_INVOICE_FROM.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "InvoiceDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/InvoiceDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableHC_ORD_INVOICE_FROM = new HC_ORD_INVOICE_FROMDataTable();
            base.Tables.Add(this.tableHC_ORD_INVOICE_FROM);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeHC_ORD_INVOICE_FROM() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            InvoiceDataSet ds = new InvoiceDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void HC_ORD_INVOICE_FROMRowChangeEventHandler(object sender, HC_ORD_INVOICE_FROMRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class HC_ORD_INVOICE_FROMDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnINVOICE_CODE;
            
            private global::System.Data.DataColumn columnBUYER_NAME;
            
            private global::System.Data.DataColumn columnsender_name;
            
            private global::System.Data.DataColumn columnOVER_SUM;
            
            private global::System.Data.DataColumn columnSTATE;
            
            private global::System.Data.DataColumn columnBUYER_DESCRIPTIONS;
            
            private global::System.Data.DataColumn columnCREATE_USER_NAME;
            
            private global::System.Data.DataColumn columnCREATE_DATE;
            
            private global::System.Data.DataColumn columnproduct_name;
            
            private global::System.Data.DataColumn columncommon_name;
            
            private global::System.Data.DataColumn columnspec;
            
            private global::System.Data.DataColumn columnmodel;
            
            private global::System.Data.DataColumn columnmanufacture_name;
            
            private global::System.Data.DataColumn columntrade_price;
            
            private global::System.Data.DataColumn columnamount;
            
            private global::System.Data.DataColumn columnover_amount;
            
            private global::System.Data.DataColumn columnitem_state;
            
            private global::System.Data.DataColumn columntotal_sum;
            
            private global::System.Data.DataColumn columnhospname;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public HC_ORD_INVOICE_FROMDataTable() {
                this.TableName = "HC_ORD_INVOICE_FROM";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal HC_ORD_INVOICE_FROMDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected HC_ORD_INVOICE_FROMDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn INVOICE_CODEColumn {
                get {
                    return this.columnINVOICE_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BUYER_NAMEColumn {
                get {
                    return this.columnBUYER_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sender_nameColumn {
                get {
                    return this.columnsender_name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OVER_SUMColumn {
                get {
                    return this.columnOVER_SUM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn STATEColumn {
                get {
                    return this.columnSTATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BUYER_DESCRIPTIONSColumn {
                get {
                    return this.columnBUYER_DESCRIPTIONS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREATE_USER_NAMEColumn {
                get {
                    return this.columnCREATE_USER_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREATE_DATEColumn {
                get {
                    return this.columnCREATE_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn product_nameColumn {
                get {
                    return this.columnproduct_name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn common_nameColumn {
                get {
                    return this.columncommon_name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn specColumn {
                get {
                    return this.columnspec;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn modelColumn {
                get {
                    return this.columnmodel;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn manufacture_nameColumn {
                get {
                    return this.columnmanufacture_name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn trade_priceColumn {
                get {
                    return this.columntrade_price;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn amountColumn {
                get {
                    return this.columnamount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn over_amountColumn {
                get {
                    return this.columnover_amount;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn item_stateColumn {
                get {
                    return this.columnitem_state;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn total_sumColumn {
                get {
                    return this.columntotal_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn hospnameColumn {
                get {
                    return this.columnhospname;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public HC_ORD_INVOICE_FROMRow this[int index] {
                get {
                    return ((HC_ORD_INVOICE_FROMRow)(this.Rows[index]));
                }
            }
            
            public event HC_ORD_INVOICE_FROMRowChangeEventHandler HC_ORD_INVOICE_FROMRowChanging;
            
            public event HC_ORD_INVOICE_FROMRowChangeEventHandler HC_ORD_INVOICE_FROMRowChanged;
            
            public event HC_ORD_INVOICE_FROMRowChangeEventHandler HC_ORD_INVOICE_FROMRowDeleting;
            
            public event HC_ORD_INVOICE_FROMRowChangeEventHandler HC_ORD_INVOICE_FROMRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddHC_ORD_INVOICE_FROMRow(HC_ORD_INVOICE_FROMRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public HC_ORD_INVOICE_FROMRow AddHC_ORD_INVOICE_FROMRow(
                        string INVOICE_CODE, 
                        string BUYER_NAME, 
                        string sender_name, 
                        decimal OVER_SUM, 
                        string STATE, 
                        string BUYER_DESCRIPTIONS, 
                        string CREATE_USER_NAME, 
                        System.DateTime CREATE_DATE, 
                        string product_name, 
                        string common_name, 
                        string spec, 
                        string model, 
                        string manufacture_name, 
                        decimal trade_price, 
                        decimal amount, 
                        decimal over_amount, 
                        string item_state, 
                        decimal total_sum, 
                        string hospname) {
                HC_ORD_INVOICE_FROMRow rowHC_ORD_INVOICE_FROMRow = ((HC_ORD_INVOICE_FROMRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        INVOICE_CODE,
                        BUYER_NAME,
                        sender_name,
                        OVER_SUM,
                        STATE,
                        BUYER_DESCRIPTIONS,
                        CREATE_USER_NAME,
                        CREATE_DATE,
                        product_name,
                        common_name,
                        spec,
                        model,
                        manufacture_name,
                        trade_price,
                        amount,
                        over_amount,
                        item_state,
                        total_sum,
                        hospname};
                rowHC_ORD_INVOICE_FROMRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowHC_ORD_INVOICE_FROMRow);
                return rowHC_ORD_INVOICE_FROMRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                HC_ORD_INVOICE_FROMDataTable cln = ((HC_ORD_INVOICE_FROMDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new HC_ORD_INVOICE_FROMDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnINVOICE_CODE = base.Columns["INVOICE_CODE"];
                this.columnBUYER_NAME = base.Columns["BUYER_NAME"];
                this.columnsender_name = base.Columns["sender_name"];
                this.columnOVER_SUM = base.Columns["OVER_SUM"];
                this.columnSTATE = base.Columns["STATE"];
                this.columnBUYER_DESCRIPTIONS = base.Columns["BUYER_DESCRIPTIONS"];
                this.columnCREATE_USER_NAME = base.Columns["CREATE_USER_NAME"];
                this.columnCREATE_DATE = base.Columns["CREATE_DATE"];
                this.columnproduct_name = base.Columns["product_name"];
                this.columncommon_name = base.Columns["common_name"];
                this.columnspec = base.Columns["spec"];
                this.columnmodel = base.Columns["model"];
                this.columnmanufacture_name = base.Columns["manufacture_name"];
                this.columntrade_price = base.Columns["trade_price"];
                this.columnamount = base.Columns["amount"];
                this.columnover_amount = base.Columns["over_amount"];
                this.columnitem_state = base.Columns["item_state"];
                this.columntotal_sum = base.Columns["total_sum"];
                this.columnhospname = base.Columns["hospname"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnINVOICE_CODE = new global::System.Data.DataColumn("INVOICE_CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINVOICE_CODE);
                this.columnBUYER_NAME = new global::System.Data.DataColumn("BUYER_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBUYER_NAME);
                this.columnsender_name = new global::System.Data.DataColumn("sender_name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsender_name);
                this.columnOVER_SUM = new global::System.Data.DataColumn("OVER_SUM", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOVER_SUM);
                this.columnSTATE = new global::System.Data.DataColumn("STATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTATE);
                this.columnBUYER_DESCRIPTIONS = new global::System.Data.DataColumn("BUYER_DESCRIPTIONS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBUYER_DESCRIPTIONS);
                this.columnCREATE_USER_NAME = new global::System.Data.DataColumn("CREATE_USER_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_USER_NAME);
                this.columnCREATE_DATE = new global::System.Data.DataColumn("CREATE_DATE", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_DATE);
                this.columnproduct_name = new global::System.Data.DataColumn("product_name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnproduct_name);
                this.columncommon_name = new global::System.Data.DataColumn("common_name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncommon_name);
                this.columnspec = new global::System.Data.DataColumn("spec", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnspec);
                this.columnmodel = new global::System.Data.DataColumn("model", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmodel);
                this.columnmanufacture_name = new global::System.Data.DataColumn("manufacture_name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmanufacture_name);
                this.columntrade_price = new global::System.Data.DataColumn("trade_price", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntrade_price);
                this.columnamount = new global::System.Data.DataColumn("amount", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnamount);
                this.columnover_amount = new global::System.Data.DataColumn("over_amount", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnover_amount);
                this.columnitem_state = new global::System.Data.DataColumn("item_state", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnitem_state);
                this.columntotal_sum = new global::System.Data.DataColumn("total_sum", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_sum);
                this.columnhospname = new global::System.Data.DataColumn("hospname", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhospname);
                this.columnINVOICE_CODE.AllowDBNull = false;
                this.columnINVOICE_CODE.MaxLength = 50;
                this.columnBUYER_NAME.AllowDBNull = false;
                this.columnBUYER_NAME.MaxLength = 150;
                this.columnsender_name.AllowDBNull = false;
                this.columnsender_name.MaxLength = 150;
                this.columnOVER_SUM.AllowDBNull = false;
                this.columnSTATE.AllowDBNull = false;
                this.columnSTATE.MaxLength = 1;
                this.columnBUYER_DESCRIPTIONS.MaxLength = 512;
                this.columnCREATE_USER_NAME.AllowDBNull = false;
                this.columnCREATE_USER_NAME.MaxLength = 200;
                this.columnCREATE_DATE.AllowDBNull = false;
                this.columnproduct_name.MaxLength = 100;
                this.columncommon_name.MaxLength = 100;
                this.columnspec.MaxLength = 4000;
                this.columnmodel.MaxLength = 3000;
                this.columnmanufacture_name.MaxLength = 150;
                this.columnitem_state.MaxLength = 1;
                this.columntotal_sum.AllowDBNull = false;
                this.columnhospname.ReadOnly = true;
                this.columnhospname.MaxLength = 164;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public HC_ORD_INVOICE_FROMRow NewHC_ORD_INVOICE_FROMRow() {
                return ((HC_ORD_INVOICE_FROMRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new HC_ORD_INVOICE_FROMRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(HC_ORD_INVOICE_FROMRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.HC_ORD_INVOICE_FROMRowChanged != null)) {
                    this.HC_ORD_INVOICE_FROMRowChanged(this, new HC_ORD_INVOICE_FROMRowChangeEvent(((HC_ORD_INVOICE_FROMRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.HC_ORD_INVOICE_FROMRowChanging != null)) {
                    this.HC_ORD_INVOICE_FROMRowChanging(this, new HC_ORD_INVOICE_FROMRowChangeEvent(((HC_ORD_INVOICE_FROMRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.HC_ORD_INVOICE_FROMRowDeleted != null)) {
                    this.HC_ORD_INVOICE_FROMRowDeleted(this, new HC_ORD_INVOICE_FROMRowChangeEvent(((HC_ORD_INVOICE_FROMRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.HC_ORD_INVOICE_FROMRowDeleting != null)) {
                    this.HC_ORD_INVOICE_FROMRowDeleting(this, new HC_ORD_INVOICE_FROMRowChangeEvent(((HC_ORD_INVOICE_FROMRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveHC_ORD_INVOICE_FROMRow(HC_ORD_INVOICE_FROMRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                InvoiceDataSet ds = new InvoiceDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "HC_ORD_INVOICE_FROMDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class HC_ORD_INVOICE_FROMRow : global::System.Data.DataRow {
            
            private HC_ORD_INVOICE_FROMDataTable tableHC_ORD_INVOICE_FROM;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal HC_ORD_INVOICE_FROMRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableHC_ORD_INVOICE_FROM = ((HC_ORD_INVOICE_FROMDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string INVOICE_CODE {
                get {
                    return ((string)(this[this.tableHC_ORD_INVOICE_FROM.INVOICE_CODEColumn]));
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.INVOICE_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BUYER_NAME {
                get {
                    return ((string)(this[this.tableHC_ORD_INVOICE_FROM.BUYER_NAMEColumn]));
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.BUYER_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string sender_name {
                get {
                    return ((string)(this[this.tableHC_ORD_INVOICE_FROM.sender_nameColumn]));
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.sender_nameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal OVER_SUM {
                get {
                    return ((decimal)(this[this.tableHC_ORD_INVOICE_FROM.OVER_SUMColumn]));
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.OVER_SUMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string STATE {
                get {
                    return ((string)(this[this.tableHC_ORD_INVOICE_FROM.STATEColumn]));
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.STATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BUYER_DESCRIPTIONS {
                get {
                    try {
                        return ((string)(this[this.tableHC_ORD_INVOICE_FROM.BUYER_DESCRIPTIONSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“HC_ORD_INVOICE_FROM”中列“BUYER_DESCRIPTIONS”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.BUYER_DESCRIPTIONSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CREATE_USER_NAME {
                get {
                    return ((string)(this[this.tableHC_ORD_INVOICE_FROM.CREATE_USER_NAMEColumn]));
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.CREATE_USER_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime CREATE_DATE {
                get {
                    return ((global::System.DateTime)(this[this.tableHC_ORD_INVOICE_FROM.CREATE_DATEColumn]));
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.CREATE_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string product_name {
                get {
                    try {
                        return ((string)(this[this.tableHC_ORD_INVOICE_FROM.product_nameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“HC_ORD_INVOICE_FROM”中列“product_name”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.product_nameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string common_name {
                get {
                    try {
                        return ((string)(this[this.tableHC_ORD_INVOICE_FROM.common_nameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“HC_ORD_INVOICE_FROM”中列“common_name”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.common_nameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string spec {
                get {
                    try {
                        return ((string)(this[this.tableHC_ORD_INVOICE_FROM.specColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“HC_ORD_INVOICE_FROM”中列“spec”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.specColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string model {
                get {
                    try {
                        return ((string)(this[this.tableHC_ORD_INVOICE_FROM.modelColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“HC_ORD_INVOICE_FROM”中列“model”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.modelColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string manufacture_name {
                get {
                    try {
                        return ((string)(this[this.tableHC_ORD_INVOICE_FROM.manufacture_nameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“HC_ORD_INVOICE_FROM”中列“manufacture_name”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.manufacture_nameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal trade_price {
                get {
                    try {
                        return ((decimal)(this[this.tableHC_ORD_INVOICE_FROM.trade_priceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“HC_ORD_INVOICE_FROM”中列“trade_price”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.trade_priceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal amount {
                get {
                    try {
                        return ((decimal)(this[this.tableHC_ORD_INVOICE_FROM.amountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“HC_ORD_INVOICE_FROM”中列“amount”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.amountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal over_amount {
                get {
                    try {
                        return ((decimal)(this[this.tableHC_ORD_INVOICE_FROM.over_amountColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“HC_ORD_INVOICE_FROM”中列“over_amount”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.over_amountColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string item_state {
                get {
                    try {
                        return ((string)(this[this.tableHC_ORD_INVOICE_FROM.item_stateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“HC_ORD_INVOICE_FROM”中列“item_state”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.item_stateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal total_sum {
                get {
                    return ((decimal)(this[this.tableHC_ORD_INVOICE_FROM.total_sumColumn]));
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.total_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string hospname {
                get {
                    try {
                        return ((string)(this[this.tableHC_ORD_INVOICE_FROM.hospnameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“HC_ORD_INVOICE_FROM”中列“hospname”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableHC_ORD_INVOICE_FROM.hospnameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBUYER_DESCRIPTIONSNull() {
                return this.IsNull(this.tableHC_ORD_INVOICE_FROM.BUYER_DESCRIPTIONSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBUYER_DESCRIPTIONSNull() {
                this[this.tableHC_ORD_INVOICE_FROM.BUYER_DESCRIPTIONSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isproduct_nameNull() {
                return this.IsNull(this.tableHC_ORD_INVOICE_FROM.product_nameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setproduct_nameNull() {
                this[this.tableHC_ORD_INVOICE_FROM.product_nameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iscommon_nameNull() {
                return this.IsNull(this.tableHC_ORD_INVOICE_FROM.common_nameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setcommon_nameNull() {
                this[this.tableHC_ORD_INVOICE_FROM.common_nameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsspecNull() {
                return this.IsNull(this.tableHC_ORD_INVOICE_FROM.specColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetspecNull() {
                this[this.tableHC_ORD_INVOICE_FROM.specColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsmodelNull() {
                return this.IsNull(this.tableHC_ORD_INVOICE_FROM.modelColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetmodelNull() {
                this[this.tableHC_ORD_INVOICE_FROM.modelColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ismanufacture_nameNull() {
                return this.IsNull(this.tableHC_ORD_INVOICE_FROM.manufacture_nameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setmanufacture_nameNull() {
                this[this.tableHC_ORD_INVOICE_FROM.manufacture_nameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Istrade_priceNull() {
                return this.IsNull(this.tableHC_ORD_INVOICE_FROM.trade_priceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Settrade_priceNull() {
                this[this.tableHC_ORD_INVOICE_FROM.trade_priceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsamountNull() {
                return this.IsNull(this.tableHC_ORD_INVOICE_FROM.amountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetamountNull() {
                this[this.tableHC_ORD_INVOICE_FROM.amountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isover_amountNull() {
                return this.IsNull(this.tableHC_ORD_INVOICE_FROM.over_amountColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setover_amountNull() {
                this[this.tableHC_ORD_INVOICE_FROM.over_amountColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isitem_stateNull() {
                return this.IsNull(this.tableHC_ORD_INVOICE_FROM.item_stateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setitem_stateNull() {
                this[this.tableHC_ORD_INVOICE_FROM.item_stateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IshospnameNull() {
                return this.IsNull(this.tableHC_ORD_INVOICE_FROM.hospnameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SethospnameNull() {
                this[this.tableHC_ORD_INVOICE_FROM.hospnameColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class HC_ORD_INVOICE_FROMRowChangeEvent : global::System.EventArgs {
            
            private HC_ORD_INVOICE_FROMRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public HC_ORD_INVOICE_FROMRowChangeEvent(HC_ORD_INVOICE_FROMRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public HC_ORD_INVOICE_FROMRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace Emedchina.TradeAssistant.Client.UI.Report.ReportData.InvoiceDataSetTableAdapters {
    
    
    /// <summary>
    ///Represents the connection and commands used to retrieve and save data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.ComponentModel.DataObjectAttribute(true)]
    [global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class HC_ORD_INVOICE_FROMTableAdapter : global::System.ComponentModel.Component {
        
        private global::System.Data.SqlClient.SqlDataAdapter _adapter;
        
        private global::System.Data.SqlClient.SqlConnection _connection;
        
        private global::System.Data.SqlClient.SqlCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public HC_ORD_INVOICE_FROMTableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Data.SqlClient.SqlDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal global::System.Data.SqlClient.SqlConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((global::System.Data.SqlClient.SqlCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected global::System.Data.SqlClient.SqlCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new global::System.Data.SqlClient.SqlDataAdapter();
            global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "HC_ORD_INVOICE_FROM";
            tableMapping.ColumnMappings.Add("INVOICE_CODE", "INVOICE_CODE");
            tableMapping.ColumnMappings.Add("BUYER_NAME", "BUYER_NAME");
            tableMapping.ColumnMappings.Add("sender_name", "sender_name");
            tableMapping.ColumnMappings.Add("OVER_SUM", "OVER_SUM");
            tableMapping.ColumnMappings.Add("STATE", "STATE");
            tableMapping.ColumnMappings.Add("BUYER_DESCRIPTIONS", "BUYER_DESCRIPTIONS");
            tableMapping.ColumnMappings.Add("CREATE_USER_NAME", "CREATE_USER_NAME");
            tableMapping.ColumnMappings.Add("CREATE_DATE", "CREATE_DATE");
            tableMapping.ColumnMappings.Add("product_name", "product_name");
            tableMapping.ColumnMappings.Add("common_name", "common_name");
            tableMapping.ColumnMappings.Add("spec", "spec");
            tableMapping.ColumnMappings.Add("model", "model");
            tableMapping.ColumnMappings.Add("manufacture_name", "manufacture_name");
            tableMapping.ColumnMappings.Add("trade_price", "trade_price");
            tableMapping.ColumnMappings.Add("amount", "amount");
            tableMapping.ColumnMappings.Add("over_amount", "over_amount");
            tableMapping.ColumnMappings.Add("item_state", "item_state");
            tableMapping.ColumnMappings.Add("total_sum", "total_sum");
            tableMapping.ColumnMappings.Add("hospname", "hospname");
            this._adapter.TableMappings.Add(tableMapping);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new global::System.Data.SqlClient.SqlConnection();
            this._connection.ConnectionString = global::Emedchina.TradeAssistant.Client.Properties.Settings.Default.TradeAssistantConnectionString;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new global::System.Data.SqlClient.SqlCommand[1];
            this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = @"select hf.INVOICE_CODE,
       hf.STATE,
       hf.BUYER_NAME,
       hf.buyer_name + '确认发货单报表' as hospname,
       hf.sender_name,
       hf.total_sum,
       hf.OVER_SUM,
       hf.CREATE_DATE,
       hf.CREATE_USER_NAME,
       hf.BUYER_DESCRIPTIONS,
       hi.product_name,
       hi.common_name,
       hi.spec,
       hi.model,  
       hi.manufacture_name,
       hi.trade_price,
       hi.amount,
       hi.over_amount,
       hi.state as item_state       
       from hc_ord_invoice_from hf left join hc_ord_invoice_from_item hi 
       on hf.id = hi.INVOICE_FROM_ID";
            this._commandCollection[0].CommandType = global::System.Data.CommandType.Text;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(InvoiceDataSet.HC_ORD_INVOICE_FROMDataTable dataTable) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual InvoiceDataSet.HC_ORD_INVOICE_FROMDataTable GetData() {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            InvoiceDataSet.HC_ORD_INVOICE_FROMDataTable dataTable = new InvoiceDataSet.HC_ORD_INVOICE_FROMDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
    }
}

#pragma warning restore 1591